### ISSUE TITLE
Implement: very short story for 100 prize

### ISSUE THREAD

**Issue by nagisc007** [nagisc007/prj_estar#53]
１００回向けの掌編
===

**Description**
文字確認とコンテスト参加確認を含めて、１００文字の掌編を作る。

**Tasks**
- [x] Prepare files
- [x] Implement story
- [x] Implement production
- [x] Upload to site
- [x] is number equal 100 on site
- [x] Is success entry to contest

**Note**
additional comment.
